import { Search, SlidersHorizontal } from 'lucide-react';
import { demoLeads, statusStyles } from '../../data/admin';

export function AdminLeads() {
  return (
    <div className="mx-auto max-w-7xl">
      <div className="mb-10"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[var(--color-accent)]">Pipeline</p><h1 className="mt-2 font-display text-5xl tracking-wide sm:text-6xl">Leads</h1><p className="mt-3 text-sm text-[var(--color-text-muted)]">Every website enquiry will appear here once Supabase is connected.</p></div>
      <div className="mb-5 flex flex-col gap-3 sm:flex-row"><label className="flex flex-1 items-center gap-3 border border-[var(--color-border-subtle)] bg-[var(--color-card-bg)] px-4 py-3"><Search size={18} className="text-[var(--color-text-muted)]" /><input className="w-full bg-transparent text-sm outline-none placeholder:text-[var(--color-text-muted)]" placeholder="Search name, company, or service" /></label><button className="inline-flex items-center justify-center gap-2 border border-[var(--color-border-subtle)] px-4 py-3 text-sm font-semibold hover:bg-[var(--color-border-subtle)]"><SlidersHorizontal size={17} />Filters</button></div>
      <div className="overflow-hidden border border-[var(--color-border-subtle)] bg-[var(--color-card-bg)]"><div className="hidden grid-cols-[1.25fr_1.1fr_0.9fr_0.85fr_0.8fr] gap-4 border-b border-[var(--color-border-subtle)] px-6 py-4 text-xs font-semibold uppercase tracking-[0.12em] text-[var(--color-text-muted)] md:grid"><span>Lead</span><span>Service</span><span>Source</span><span>Status</span><span>Received</span></div>{demoLeads.map((lead) => <article key={lead.id} className="grid gap-3 border-b border-[var(--color-border-subtle)] px-5 py-5 last:border-0 md:grid-cols-[1.25fr_1.1fr_0.9fr_0.85fr_0.8fr] md:items-center md:gap-4 md:px-6"><div><p className="font-semibold">{lead.name}</p><p className="mt-1 text-sm text-[var(--color-text-muted)]">{lead.company} · {lead.email}</p></div><p className="text-sm"><span className="mr-2 text-xs font-semibold uppercase tracking-wide text-[var(--color-text-muted)] md:hidden">Service</span>{lead.service}</p><p className="text-sm"><span className="mr-2 text-xs font-semibold uppercase tracking-wide text-[var(--color-text-muted)] md:hidden">Source</span>{lead.source}</p><div><span className={`inline-flex border px-2.5 py-1 text-xs font-semibold ${statusStyles[lead.status]}`}>{lead.status}</span></div><p className="text-sm text-[var(--color-text-muted)]">{lead.receivedAt}</p></article>)}</div>
    </div>
  );
}
